# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('agent_port', models.IntegerField(blank=True, null=True, verbose_name='\u4ee3\u7406\u7aef\u53e3')),
                ('app_port', models.IntegerField(blank=True, null=True, verbose_name='\u5e94\u7528\u7aef\u53e3')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['name', 'agent_ip', 'agent_port', 'app_ip'],
                'verbose_name': '\u5e94\u7528\u4ee3\u7406\u8868',
                'verbose_name_plural': '\u5e94\u7528\u4ee3\u7406\u8868',
                'permissions': (('view_agent', 'View agent'),),
            },
        ),
        migrations.CreateModel(
            name='BankTunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4e13\u7ebf\u540d\u79f0')),
                ('bank_ip', models.GenericIPAddressField(verbose_name='\u5bf9\u7aefIP')),
                ('local_ip', models.GenericIPAddressField(verbose_name='\u672c\u7aefIP')),
                ('bank_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5bf9\u7aef\u4e1a\u52a1')),
                ('local_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u672c\u7aef\u4e1a\u52a1')),
                ('tech_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6280\u672f\u8c03\u8bd5')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('script', models.TextField(blank=True, null=True, verbose_name='\u521b\u5efa\u811a\u672c')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u4e13\u7ebf\u7ba1\u7406',
                'verbose_name_plural': '\u4e13\u7ebf\u7ba1\u7406',
                'permissions': (('view_banktunnel', 'View banktunnel'),),
            },
        ),
        migrations.CreateModel(
            name='LanIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ip', models.GenericIPAddressField(verbose_name='LAN_IP')),
                ('area', models.CharField(default='INSIDE', max_length=20, verbose_name='\u533a\u57df')),
                ('status', models.NullBooleanField(choices=[(True, '\u5728\u7528'), (False, '\u7a7a\u95f2'), (None, '\u672a\u77e5')], default=True, verbose_name='\u72b6\u6001')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u8be6\u7ec6\u4fe1\u606f')),
            ],
            options={
                'ordering': ['l_ip'],
                'verbose_name': '\u5185\u7f51\u5730\u5740\u7ba1\u7406',
                'verbose_name_plural': '\u5185\u7f51\u5730\u5740\u7ba1\u7406',
                'permissions': (('view_lanip', 'View LanIp'),),
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u6620\u5c04\u540d')),
                ('w_port', models.IntegerField(blank=True, null=True, verbose_name='WAN_PORT')),
                ('l_port', models.IntegerField(blank=True, null=True, verbose_name='LAN_PORT')),
                ('scripts', models.TextField(blank=True, null=True, verbose_name='\u521b\u5efa\u811a\u672c')),
                ('map_user', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='\u7528\u6237')),
                ('map_date', models.DateField(verbose_name='\u5f00\u901a\u65e5\u671f')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u529f\u80fd\u63cf\u8ff0')),
                ('l_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanIp_Set', to='portmap.LanIp', verbose_name='LAN_IP')),
            ],
            options={
                'ordering': ['w_ip', 'w_port', 'l_ip', 'l_port'],
                'verbose_name': '\u7aef\u53e3\u6620\u5c04\u7ba1\u7406',
                'verbose_name_plural': '\u7aef\u53e3\u6620\u5c04\u7ba1\u7406',
                'permissions': (('view_maps', 'View maps'),),
            },
        ),
        migrations.CreateModel(
            name='WanIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_ip', models.GenericIPAddressField(unique=True, verbose_name='WAN_IP')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['w_ip'],
                'verbose_name': '\u516c\u7f51\u5730\u5740\u7ba1\u7406',
                'verbose_name_plural': '\u516c\u7f51\u5730\u5740\u7ba1\u7406',
                'permissions': (('view_wanip', 'View WanIp'),),
            },
        ),
        migrations.AddField(
            model_name='maps',
            name='w_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WanIp_Set', to='portmap.WanIp', verbose_name='WAN_IP'),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanIp_Set_2', to='portmap.LanIp', verbose_name='\u4ee3\u7406IP'),
        ),
        migrations.AddField(
            model_name='agent',
            name='app_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanIp_Set_3', to='portmap.LanIp', verbose_name='\u5e94\u7528IP'),
        ),
    ]
