# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('website', models.CharField(max_length=150, verbose_name='\u5730\u5740')),
                ('show', models.BooleanField(choices=[(True, '\u663e\u793a'), (False, '\u4e0d\u663e\u793a')], default=True, verbose_name='\u663e\u793a')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5feb\u6377\u94fe\u63a5',
                'verbose_name_plural': '\u5feb\u6377\u94fe\u63a5',
            },
        ),
    ]
